MODULE IDXCON_DAT
!
! VERSION
!   01MAY17 AD F90 conversion. Checked.
!
! DESCRIPTION
!   RFM/HITRAN indices for specific molecules
!   Should be consistent with definitions in MOLIDX
!
! VARIABLE KINDS
    USE KIND_DAT 
!
  IMPLICIT NONE
!
! GLOBAL CONSTANTS
    INTEGER(I4), PARAMETER :: IDXH2O = 1 
    INTEGER(I4), PARAMETER :: IDXCO2 = 2
    INTEGER(I4), PARAMETER :: IDXCH4 = 6
    INTEGER(I4), PARAMETER :: IDXO2  = 7 
    INTEGER(I4), PARAMETER :: IDXN2  = 22
    INTEGER(I4), PARAMETER :: IDXAIR = 99   ! RFM-specific
    INTEGER(I4), PARAMETER :: IDXAER = 100  ! RFM-specific
!
END MODULE IDXCON_DAT

